# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://panchinabil.github.io/sea_ice_segmentation/"

git_url = "https://github.com/panchinabil/sea_ice_segmentation/tree/master/"

def custom_doc_links(name): return None
